# Generated by Django 5.1.6 on 2025-02-24 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swirl', '0005_alter_searchprovider_connector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchprovider',
            name='connector',
            field=models.CharField(choices=[('ChatGPT', 'ChatGPT Query String'), ('GenAI', 'Generative AI'), ('RequestsGet', 'HTTP/GET returning JSON'), ('RequestsPost', 'HTTP/POST returning JSON'), ('Elastic', 'Elasticsearch Query String'), ('OpenSearch', 'OpenSearch Query String'), ('QdrantDB', 'QdrantDB'), ('PostgreSQL', 'PostgreSQL'), ('BigQuery', 'Google BigQuery'), ('Sqlite3', 'Sqlite3'), ('M365OutlookMessages', 'M365 Outlook Messages'), ('M365OneDrive', 'M365 One Drive'), ('M365OutlookCalendar', 'M365 Outlook Calendar'), ('M365SharePointSites', 'M365 SharePoint Sites'), ('MicrosoftTeams', 'Microsoft Teams'), ('MongoDB', 'MongoDB'), ('Oracle', 'Oracle'), ('Snowflake', 'Snowflake'), ('PineconeDB', 'PineconeDB')], default='RequestsGet', max_length=200),
        ),
    ]
